### ISSUE TITLE
1.11.2 compatibility issue.

### ISSUE THREAD

**Issue by Wissi** [2piradians/Block-Armor#1]
Using BlockArmor-1.11-2.0.jar
When trying to use it on Minecraft version 1.11.2 it will crash.

I know it's only for 1.11

Most 1.11 mods are compatible with 1.11.2
Can your mod be 1.11.2 compatible soon?

Ur mod is awesome and we would like to use it on our 1.11.2 mod server as well.
thanks.

**Comment by 2piradians** [comment]
This is not an issue; you are simply using an incompatible version. While, yes, it is _often_ the case that versions are forward compatible when the only difference is #.##.X, it is a bad idea to assume mods are compatible with newer versions than what they are listed as, since methods can change between any two Forge releases.

With that said, yes, it will be updated to 1.11.2, but only when Forge comes out with a recommended, stable version. Last I checked, they did not have a stable version yet. If you would like, and if I have not updated already, you can leave a comment on CurseForge when you see that Forge has posted a recommended version for 1.11.2, and I can work on the update then.

**Comment by Furgl** [comment]
Block Armor has now been ported to 1.11.2
