### ISSUE TITLE
[TConstruct] Cobalt Armor missing

### ISSUE THREAD

**Issue by ghost** [2piradians/Block-Armor#14]
Minecraft: 1.12.1
Block Armor version: 2.4.7

When Tinkers Construct is installed along with the [Chisel](https://minecraft.curseforge.com/projects/chisel) mod, there is no Cobalt Armor generated, even if the Cobalt Armor in the Chisel section of the config is set to false.

**Comment by Furgl** [comment]
I would assume that this is because the mod only allows one armor set to have a registration name from a "Cobalt" block. Since both Tinkers' Construct and Chisel have a Cobalt block, the mod chooses to create Cobalt armor from Chisel's Cobalt block. Unfortunately, Chisel's blocks use unusual texture mapping so the mod is unable to find their textures and automatically disables the Cobalt armor set. Unfortunately, there's not much we can do to fix this.

**Comment by ghost** [comment]
The armor is generated when Cobalt is set to false in the Chisel config.
