### ISSUE TITLE
BUG: Chisel mod added blocks can't create armor

### ISSUE THREAD

**Issue by werff** [2piradians/Block-Armor#18]
Just that, in the newest 1.12.X version I have that problem, I tryed to enable paper blokc armor, and other 2 and they didn't generate and config reseted :/

**Comment by Furgl** [comment]
Blocks from Chisel map their textures in a unique way that makes it difficult for the mod to find them properly. Because our mod cannot find the textures for the blocks, it automatically disables the armor set. We may look at Chisel in the future and see if we can find a way to map their textures properly.
