### ISSUE TITLE
Crash-Max Id Reached

### ISSUE THREAD

**Issue by WenXin20** [2piradians/Block-Armor#3]
MIt would be nice to be able to limit the max amount of modded block armors that can register. The reason is that my game ran out of ids to use, so it just crashes the game that says it exceded the max id.

I also tried disabling some of the modded armors, but the config reset on reload changed it back. So I don't  know if it's a glitch or because the game didn't load completely before it crashed.

**Comment by Furgl** [comment]
From what we can find on the subject, it seems like Minecraft allows item ID's up to 32,767. In a very large mod pack I could see Block Armor generating around 1-2k items, which is a LOT of items for a mod. Even with 100s of other mods, I don't think they would ever be able to generate over 30k items (probably around 3-4k for 100 mods), unless they are doing something wrong.

Could you give us the crash log and fml-client log for us to look at? Do you know how to replicate the problem? 

Also, once an item is loaded into Minecraft, an item ID is assigned to it and will not normally be changed, even when the mod is uninstalled or the items are not generated anymore; so disabling items or stopping them from being registered again will not change anything. 

As for your config being reset on reloading, this is an issue we have never encountered or heard of happening. If you can find a way to replicate this issue, we can try to fix it; otherwise I would assume it was just a glitch from the game crashing while loading.

**Comment by WenXin20** [comment]
I have maybe more than 200 mods that adds blocks. It registered about 5,500 armor sets. It also didn't crash after disabling the option for Auto-Generate Armor Sets.
Here is the crash report: http://pastebin.com/jbrgGknb
Since the new minecraft luancher is being used, the latest.log doesn't save, so I don't have that log with the crash yet.

**Comment by Furgl** [comment]
Well, first of all, I'm very impressed/surprised that you can manage to load up a mod pack with 421 mods in the first place. You can stop sets from being registered individually in the config, or all together with the Auto-Generate Armor Sets option (the config will be completely redone, to be more convenient to use, in the next update). If you've been adding/removing mods a lot, that can also use up a lot of item ID's; loading the pack on a new world will reset that.

**Comment by WenXin20** [comment]
Ok, thanks
